### ISSUE TITLE
UIButton action not appear 

### ISSUE THREAD

**Issue by bokhary3** [MoathOthman/MOLH#1]
After downloading your awesome pod I faced problem where I can't add Action connection for button from storyboard I get only outlet and collection outlet connections , But After searching I get the error is that in MOLHFontLocalizableViews.swift file you conforms MOLHFontable protocol and after delete conform of protocol the action connect return again , so please check this issue.
Thanks

**Comment by MoathOthman** [comment]
Thanx for reporting that , I will check it ASAP

**Comment by MoathOthman** [comment]
Hi , it seems like a bug in xcode you may check 
https://forums.developer.apple.com/thread/25180
I checked it with xcode9b4 and it's working fine .

**Comment by bokhary3** [comment]
Ok thanks
