### ISSUE TITLE
Issue in Swift4

### ISSUE THREAD

**Issue by vaibhav319** [MoathOthman/MOLH#13]
When we change current Language to another language (english to arabic), it works fine . but now when we change language to previous one.(arabic to english) Its not working fine. UIApplication.isRTL() is false first time, when we change language , UIApplication.isRTL() is now true. but now when we change no matter in which language UIApplication.isRTL() is always true. but when we quit app and start it will change value give false and all wil work good. Can you please update it for Swift 4 or provide me the solution ?

**Comment by MoathOthman** [comment]
@vaibhav319I would suggest not to use UIApplication.isRTL() , and to use MOLHLanguage.isRTLLanguage(). please let me know if it helps

**Comment by MoathOthman** [comment]
release 0.2.0 is updated to swift 4.1
