### ISSUE TITLE
Theres 13 issues in the library 

### ISSUE THREAD

**Issue by lamatat** [MoathOthman/MOLH#15]
Hi, 
Thank you so much for this amazing library ...
i want to use it in my project but i got 13 issues in the library...

![screen shot 2018-05-28 at 10 31 28 am](https://user-images.githubusercontent.com/39458325/40602812-a0528100-6262-11e8-8345-76bd7d5c50d4.png)

would you please solve them?

thanks! :)

**Comment by lamatat** [comment]
just fixed it ...

**Comment by MoathOthman** [comment]
We will do the migration asap :)

Sent from my iPhone

On May 28, 2018, at 10:11 AM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


just fixed it ...
