### ISSUE TITLE
some subviews didn't flip

### ISSUE THREAD

**Issue by lamatat** [MoathOthman/MOLH#19]
i have in my view a navigation view ... mostly on all pages ..
strangely some of these navigation views didn't flip when change language when most of them did flip .. why?

**Comment by MoathOthman** [comment]
Depends on the view type,
Did u set the tag correctly?
Some views like uiimagevirw needs manual flipping or if u use custom constraints you may also need to do that manually.

Sent from my iPhone

On Jun 5, 2018, at 10:00 AM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


i have in my view a navigation view ... mostly on all pages ..
strangely some of these navigation views didn't flip when change language when most of them did flip .. why?

**Comment by lamatat** [comment]
which tag do you mean?
and the items which are not flipping are buttons..

**Comment by MoathOthman** [comment]
For example button.tag should be less than zero

Sent from my iPhone

On Jun 5, 2018, at 10:33 AM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


which tag do you mean?
and the items which are not flipping are buttons..

**Comment by lamatat** [comment]
just tried that .. but didn't work ...
how to flip it manually?

**Comment by MoathOthman** [comment]
Can u provide a screenshot, do u use autolayout

Sent from my iPhone

On Jun 5, 2018, at 11:02 AM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


just tried that .. but didn't work ...
how to flip it manually?

**Comment by lamatat** [comment]
here ...

![screen1](https://user-images.githubusercontent.com/39458325/40965084-8259b2a0-68b5-11e8-9193-4143485fecbd.png)

![screen2](https://user-images.githubusercontent.com/39458325/40965100-8d495684-68b5-11e8-930e-5dc440aabd94.png)

as you can see that all of the views and its items flipped .. but the button in the red circle ...

**Comment by lamatat** [comment]
any news?

**Comment by MoathOthman** [comment]
Can u provide a screenshot, do u use autolayout

Sent from my iPhone

On Jun 5, 2018, at 11:31 AM, moath othman <m_torch@hotmail.com<mailto:m_torch@hotmail.com>> wrote:

Can u provide a screenshot, do u use autolayout

**Comment by lamatat** [comment]
solved..

it was something with the constraints once updated it worked!

thanks again :)
