### ISSUE TITLE
change language like(english, arabic, chinese, korean, russian)

### ISSUE THREAD

**Issue by vikramsinghcharan** [MoathOthman/MOLH#2]
hello 

i'm newbee in ios developer. could your please tell me how to loacalize in all these language :- english, arabic, chinese, korean, russian

**Comment by MoathOthman** [comment]
Hi @vikramsinghcharan  , add string files e.g. Localizable.string.  click on your project -> projectname -> under the info tap you will find localization aria -> click on the plus button and add the languages you need.  it will ask you what you want to localize then choose the needed files e.g.  Localizable.string. 
I found this tutorial that cover the process https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881
happy coding.

**Comment by vikramsinghcharan** [comment]
Thank you very much MoathOthman for your reply. but my main problem is that while i'm using MOLH library for localization than it always access english, arabic  Localizalbe.string file. i'm not able to access any other languages Localizalbe.string file in my app. I can't see any change regarding this.

**Comment by MoathOthman** [comment]
Let me check that  .

**Comment by vikramsinghcharan** [comment]
thank you for your help. And it's nice library.

**Comment by MoathOthman** [comment]
you're very welcome
