### ISSUE TITLE
how to set language

### ISSUE THREAD

**Issue by lamatat** [MoathOthman/MOLH#20]
i have two buttons arabic and english .. when clicked on arabic i want to change language to arabic and same with english ...

so i cannot use  MOLH.setLanguageTo(MOLHLanguage.currentAppleLanguage() == "en" ? "ar" : "en")

i tried  MOLH.setLanguageTo("en") but it didn't do anything ... how to do it?

**Comment by MoathOthman** [comment]
As you are doing already , you’re need to reset the views , check the demo on how its done , it might help u

Sent from my iPhone

On Jun 6, 2018, at 1:00 PM, lamatat <notifications@github.com<mailto:notifications@github.com>> wrote:


i have two buttons arabic and english .. when clicked on arabic i want to change language to arabic and same with english ...

so i cannot use MOLH.setLanguageTo(MOLHLanguage.currentAppleLanguage() == "en" ? "ar" : "en")

i tried MOLH.setLanguageTo("en") but it didn't do anything ... how to do it?

**Comment by lamatat** [comment]
yes i did but still didn't change...
