### ISSUE TITLE
UIStackviews Doesn't change its direction until restarting the app but anything else works well

### ISSUE THREAD

**Issue by merovic** [MoathOthman/MOLH#21]

**Comment by MoathOthman** [comment]
I have not faced issues with stackViews,
What does not change the direction, stackview itself or its content !
Regards,

**Comment by merovic** [comment]
no only its content, stackview itself is changing its direction very well

**Comment by MoathOthman** [comment]
what type of contents you have ? @merovic , if you can fork the project and add an example to the demo and then post the link it would be great.

**Comment by merovic** [comment]
just 2 UILabels I added to the example itself, I gave a background color to the UILabels and a leading constrain to the UIstackview to ensure that stack view changing its direction, and i found that stack view changes its direction without any problem but the 2 uilabels inside it doesn't change their direction until I kill the application and restart it again.

I will post a link for more details.

**Comment by MoathOthman** [comment]
@merovic can you provide a link, I will debug the issue and might come up with a solution. thank you

**Comment by merovic** [comment]
That link contains the needed modification of MOLH Example Project to demonstrate the direction issue.

https://drive.google.com/open?id=1Z-3PKPeNh3JdLmHqtWoLRtea_HvPj540

**Comment by MoathOthman** [comment]
@merovic looks you missed setting the tag to less than or equal `maximumLocalizableTag` which is by default -1 , the labels tags are 0 currently , hence they wont flip.
changing the tag should be applied to all views not just labels. so make sure you have that modified  through your app.
