### ISSUE TITLE
Arabic is always the defaults language 

### ISSUE THREAD

**Issue by AliHassany** [MoathOthman/MOLH#23]
Hi, 
could you help me, what is the best way to define Arabic as the default language?

I did this in App delegate 
 MOLH.shared.activate(true)
        MOLH.setLanguageTo("ar")
        MOLH.reset()

but the problem with the TextView is not RTL, I have justified and centre text attributed alignment 

I need to restart the app to see the correct alignment

**Comment by MoathOthman** [comment]
@AliHassany can you try to use MOLHLanguage.setDefaultLanguage
