### ISSUE TITLE
how to Localize app without Restart message

### ISSUE THREAD

**Issue by NermeenMohamed** [MoathOthman/MOLH#24]
I can change language from app but it changed after restart application ,
how to do it without restart message as drawn views not reset to the new localization ?

**Comment by MoathOthman** [comment]
@NermeenMohamed did you check the demo , you need to reset the rootviewcontroller, in order for it to work.

**Comment by NermeenMohamed** [comment]
yes I checked it .. when I use MOLH it change views from RTL or LTR Fine but not localize labels it need s to restart app

**Comment by MoathOthman** [comment]
The appdelegate needs to implement the reset function and confirm to molhresetable
And there you need to reset the rootviewcontroller , do you do that ?

Sent from my iPhone

On Aug 6, 2018, at 12:40 PM, Nermeen Mohmed <notifications@github.com<mailto:notifications@github.com>> wrote:


yes I checked it .. when I use MOLH it change views from RTL or LTR Fine but not localize labels it need s to restart app
