### ISSUE TITLE
RTL Design

### ISSUE THREAD

**Issue by shayanaghajan** [MoathOthman/MOLH#25]
Is it okay to use .forceRightToLeft for right to left language instead of localize the app ??

**Comment by MoathOthman** [comment]
its already used in https://github.com/MoathOthman/MOLH/blob/1a6c011647e78d8020c7cfd4db0838c985e523d4/MOLH/MOLH.swift#L131

am not sure what are you trying to do

**Comment by shayanaghajan** [comment]
What do you do to make an RTL app ?? Do you start it RTL from beginning or make it in english and then reverse it to RTL ?

**Comment by MoathOthman** [comment]
You can do either. Check molh.setdefault method

Sent from my iPhone

On Sep 1, 2018, at 4:56 PM, shayanaghajan <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you do to make an RTL app ?? Do you start it RTL from beginning or make it in english and then reverse it to RTL ?
