### ISSUE TITLE
How to set the app default language to Arabic at app install time?

### ISSUE THREAD

**Issue by zahidshaikh795** [MoathOthman/MOLH#29]
I try to change the language to Arabic from edit schema but then RTL is not working on change language button click.Is there any way to set the default language to Arabic when the app installed for the first time.

**Comment by MoathOthman** [comment]
@zahidshaikh795 sorry for the late replay. seems like the current MOLHLanguage.setdefault method is not working probably . am going to check that these two days and provide a fix hopefully.

**Comment by MoathOthman** [comment]
Its currently working in latest release.
