### ISSUE TITLE
sometimes the back button get's flipped in a wrong way

### ISSUE THREAD

**Issue by deya-eldeen** [MoathOthman/MOLH#3]
Hello, see the back button get's flipped...

![simulator screen shot oct 5 2017 10 35 51 am](https://user-images.githubusercontent.com/7140673/31215723-5642c6c2-a9b9-11e7-819a-95322a27a698.png)

**Comment by deya-eldeen** [comment]
it looks like it's solved when I added the Arabic language as a language in the info from build settings.

**Comment by MoathOthman** [comment]
is it a custom back button or the default one?! , if its custom you need to check for the language when you create it and use the correct behavior .
e.g.

`  func setupBackButton() {
        self.navigationItem.backBarButtonItem = nil;
        var backButtonBackgroundImage = UIImage(named: "back")?.withAlignmentRectInsets(UIEdgeInsets(top: 0, left: -50, bottom: -5, right: -100))
        if MOLHLanguage.isRTL().isRTL() {
             backButtonBackgroundImage = backButtonBackgroundImage?.flippedImage()
        }
        self.navigationController?.navigationBar.backIndicatorImage = backButtonBackgroundImage
        self.navigationController?.navigationBar.backIndicatorTransitionMaskImage = backButtonBackgroundImage
        self.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: UIBarButtonItemStyle.plain, target: nil, action: nil)
    }`

Please try that .

**Comment by MoathOthman** [comment]
Aha , good to hear that. 👍
