### ISSUE TITLE
adding an option to change animation when changing language

### ISSUE THREAD

**Issue by deya-eldeen** [MoathOthman/MOLH#30]
Hello, some people asked me to change the animation transition when switching language....

I managed to make it as easy as
MOLH.resetWithCrossDissolve()

please make this a feature available for all :) , thanks.

the simplest way is to extend MOLH with a new reset function.... and call it
`MOLH.resetWithCrossDissolve()`
for example

```
extension MOLH {
    open class func resetWithCrossDissolve() {
        let transition = UIViewAnimationOptions.transitionCrossDissolve
        if let delegate = UIApplication.shared.delegate {
            if delegate is MOLHResetable {
                (delegate as!MOLHResetable).reset()
            }
            UIView.transition(with: ((delegate.window)!)!, duration: 0.5, options: transition, animations: {}) { (f) in
            }
        }
    }
}

```

**Comment by MoathOthman** [comment]
@deya-eldeen thanx for the suggestion , can you make a pull request for that?
