### ISSUE TITLE
Flip Collection flow layout flow 

### ISSUE THREAD

**Issue by MoathOthman** [MoathOthman/MOLH#34]
Flip Collection flow layout flow

**Comment by mehroozkhan** [comment]
I am getting same issue while showing UIContxtMenu,  Have a look at the attached screenshot

![Simulator Screen Shot - iPhone 11 - 2020-10-21 at 19 44 44](https://user-images.githubusercontent.com/17316374/96740844-a9f2ec00-13da-11eb-9605-14c7c6a4fc37.png)

Please help me

**Comment by MoathOthman** [comment]
you need to refresh the view some home, can you share some code @mehroozkhan

**Comment by mehroozkhan** [comment]
@MoathOthman moreover when I view it in debug view hierarchy it looks okay, 

<img width="355" alt="Screenshot 2020-10-21 at 7 51 48 PM" src="https://user-images.githubusercontent.com/17316374/96762891-edf1eb00-13f2-11eb-98c3-f428335570ef.png">

please help me its been 2 days now, I am stuck here

**Comment by MoathOthman** [comment]
@mehroozkhan can you create a small demo. i just tried context menu but not from the table view delegate and it was fine. but your case is a bit different

**Comment by mehroozkhan** [comment]
@MoathOthman you want me to create demo project or demo video ?
I used the same code in another project and that's working fine, 

For English language it works fine, getting this flipped issue only for arabic (RTL)

**Comment by MoathOthman** [comment]
demo project would be great

**Comment by MoathOthman** [comment]
@mehroozkhan did you find a way to resolve it?

**Comment by mehroozkhan** [comment]
@MoathOthman Not yet, 
actually, it's a big project, I don't know how to create a demo project out of it.

**Comment by MoathOthman** [comment]
@mehroozkhan have you tried 
` self.tableView.semanticContentAttribute = .unspecified`

**Comment by mehroozkhan** [comment]
@MoathOthman yes, did not work, 
I can't understand why it shows correctly in debug view hierarchy 

<img width="1678" alt="Screenshot 2020-10-24 at 4 02 35 PM" src="https://user-images.githubusercontent.com/17316374/97080100-769aa200-1612-11eb-84f0-3803dbb283e8.png">

**Comment by MoathOthman** [comment]
@mehroozkhan any luck ?

**Comment by mehroozkhan** [comment]
@MoathOthman Yes, I fixed it, in xcode project my development language was set to arabic, 
I changed it to english, thats it.

**Comment by MoathOthman** [comment]
@mehroozkhan  you mean the app language from the project scheme ?!
![Screen Shot 2020-11-12 at 3 23 03 PM](https://user-images.githubusercontent.com/1166727/98939752-f96c9980-24fa-11eb-8b65-198ddf33d2a3.png)

**Comment by mehroozkhan** [comment]
@MoathOthman not app language, its development language, I don't know how it got set to arabic. 

![Screen Shot 2020-11-12 at 5 26 23 PM](https://user-images.githubusercontent.com/17316374/98940427-c7fcc980-250c-11eb-96eb-419843a3f361.png)

**Comment by MoathOthman** [comment]
mm, but how do u do localization?

**Comment by mehroozkhan** [comment]
@MoathOthman I did not understand, No using localization in storyboard, 

doing localization via code only.

**Comment by MoathOthman** [comment]
I see, good to hear to worked out for you 👍
