### ISSUE TITLE
UnFlip a UIView

### ISSUE THREAD

**Issue by arunktinnovat** [MoathOthman/MOLH#38]
While switching the language to Arabic, I need a specific UIView and the UIControls inside it not to be flipped. I had tried setting the tag as -1. But it didn't worked. How to make it out?

**Comment by MoathOthman** [comment]
hey @arunktinnovat 
If you are using auto layout, then you can disable "respecting language direction"  check this SO question 
https://stackoverflow.com/questions/19916926/disable-autolayout-localization-behavior-rtl-right-to-left-behavior

**Comment by arunktinnovat** [comment]
Thank you, selecting the UIControls and unchecking the 'Respect language direction' for all the leading and trailing constraints worked :)
