### ISSUE TITLE
Prevent UIStackView from flipping 

### ISSUE THREAD

**Issue by i0sa** [MoathOthman/MOLH#39]
I tried using the maximumLocalizableTag option for stackview, and it never worked, I can't prevent it from flipping, i also looked up MOLH and didn't see any integration with stackviews, How can i prevent MOLH from flipping a stackview ? not even setting semanticContentAttribute works.

**Comment by MoathOthman** [comment]
hey @i0sa  
if you are using autolayout , then click on the left and right constraints and from the inspector uncheck "respect language direction" option. 
the flipping MOH does is for the content and has nothing to do with auto layout. 

please let me know if that helps. and if my response is not clear let me know as well.
