### ISSUE TITLE
RTL and LTR is not working with TabbarController.

### ISSUE THREAD

**Issue by EMakadiya** [MoathOthman/MOLH#4]
Hey moath

Thanks for your awesome library :)

My Project have slide menu and tabbar controller. So My app rootviewcontroller is slide menu and that side menu have center and left view controller.

So when I am trying to change language from app then side menu left and center viewcontroller's alignment is not working. All other viewcontroller's alignment is working fine.

When I relaunch app then left and center viewcontroller's alignment is working fine. but its not working when I call reset function from app.

I thinks that view's are not updating.

Please help me.

Thanks,
Ekta

**Comment by MoathOthman** [comment]
Hey Ekta, 
maybe your not restarting the views correctly , 
try using these lines when u reset the views
window?.rootViewController?.dismiss(animated:false)
window?.rootViewController = <your first view>

Best of luck
