### ISSUE TITLE
Tableview and collection view not updated when language changed

### ISSUE THREAD

**Issue by SherifKamalSalem** [MoathOthman/MOLH#42]
I have view controller with tableview and collectionview included so in cellForItemfor indexpath I grabbed out the item and use property observer to fill in cell components 

   var store: Store? {
        didSet {
            storeNameLbl.text = store?.name.localized
            if let url = store?.logoURL {
                storeImage.contentMode = .scaleAspectFill
                storeImage.sd_imageIndicator = SDWebImageActivityIndicator.grayLarge
                storeImage.sd_imageIndicator?.startAnimatingIndicator()
                storeImage.sd_setImage(with: url)
            }
      }
}
in func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
cell.store = self.stores[indexPath.row]
}

so all things changes correctly except tableview cells labels and collectionview labels

**Comment by MoathOthman** [comment]
is the label tag < 0 ?

**Comment by abdullahayyad** [comment]
when using storyboard localize it should work
but in xCode11.1  have bugs in static table view cell well not localized 
see [https://developer.apple.com/documentation/xcode_release_notes/xcode_11_1_release_notes/](url)

to fix issue you must handle it
