### ISSUE TITLE
The "fr" language is not a RTL language

### ISSUE THREAD

**Issue by medHajajate** [MoathOthman/MOLH#44]
Hi,
In your class MOLHLanguage, the RTL language array contains the "**fr**" language, you should remove it, as you know the  **fr** isn't a RTL language,

Best Regards.

**Comment by MoathOthman** [comment]
Correct, that was supposed to be fa. Will fix it asap

Sent from my iPhone

On Nov 21, 2019, at 8:18 PM, Med Hajajate <notifications@github.com> wrote:

﻿

Hi,
In your class MOLHLanguage, the RTL language array contains the "fr" language, you should remove it, as you know the fr isn't a RTL language,

Best Regards.

**Comment by MoathOthman** [comment]
fixed now , thnx for reporting.
