### ISSUE TITLE
App Getting Crashed for iOS 13

### ISSUE THREAD

**Issue by imuhammadjabbar** [MoathOthman/MOLH#48]
The app is getting crashed on .reset() function. You are using delegate.window there but "window" has been moved to SceneDelegate in iOS 13. 
UIView.transition(with: ((delegate.window)!)!, duration: 0.5, options: transition, animations: {}) { (f) in }

So, I tried to change it to sceneDelegate.window but it is still getting crashed.

Here is the screenshot for your reference: [https://imgur.com/ZuPr4RW](url)

Any workaround for now? Please let me know.

Regards,

**Comment by MoathOthman** [comment]
@imuhammadjabbar if you are not supporting iPad OS you can opt-out from using Scene delegate.

**Comment by imuhammadjabbar** [comment]
> @imuhammadjabbar if you are not supporting iPad OS with multiple scenes you can opt-out from using Scene delegate AFAIK.

But, I am setting my rootViewController in UISceneDelegate. I had implemented the reset() and MOLHResetable in UISceneDelegate as well. But still getting this crash.

**Comment by imuhammadjabbar** [comment]
> @imuhammadjabbar if you are not supporting iPad OS with multiple scenes you can opt-out from using Scene delegate AFAIK.

Any workaround you can suggest with UISceneDelegate?

**Comment by MoathOthman** [comment]
check this issue https://github.com/MoathOthman/MOLH/issues/46 , it might help but I have not tried that tbh.

**Comment by MoathOthman** [comment]
Fixed

**Comment by islamnabil** [comment]
Hi @MoathOthman ,
I have the same issue here at iOS 13 ... I don't iPad OS .. just iPhone

**Comment by MoathOthman** [comment]
@islamnabil have you check latest version. i made a fix recently for this.

**Comment by islamnabil** [comment]
yes I've installed version 1.9.1
@MoathOthman

**Comment by MoathOthman** [comment]
its v1.3 !

**Comment by islamnabil** [comment]
https://imgur.com/n33EM1l 😄

**Comment by MoathOthman** [comment]
that's actually the cocoapods version, you can find the molh version in the Podfile.lock  heh.
