### ISSUE TITLE
App is lagging after language change

### ISSUE THREAD

**Issue by vishnuprasadku** [MoathOthman/MOLH#5]
Hii , thanks for your great work. 

I got a performance issue with the pushing of new viewcontrollers after switching the langugaes. The pushing seems to be laggy. I have tried to use the main thread, but the issue is still there. Any solution for this??

**Comment by MoathOthman** [comment]
This is probably because you are not resetting the Views correctly , e.i you are not removing the previous Views and hence they stay in the memory and causes the lag,

**Comment by vishnuprasadku** [comment]
Thanks for answering,
I have resetted the root view controller successfully, even after that the
pushing of view controllers is lagging,I have tried instruments to check if
any memory leaks exists, but couldn't find anything

**Comment by MoathOthman** [comment]
hey @vishnuprasadku 
after reseting the views try to debug the hierarchy by clicking on "Debug View hierarchy" 
 
![screen shot 2018-01-12 at 16 14 49](https://user-images.githubusercontent.com/1166727/34881409-ca719882-f7b3-11e7-8bd1-2e309741d24b.png)

And see if there are hidden views that still there.

**Comment by MoathOthman** [comment]
@vishnuprasadku have you managed to solve it .
