### ISSUE TITLE
Kurdish language corrupted text

### ISSUE THREAD

**Issue by abdallahnh** [MoathOthman/MOLH#51]
I tried to use the Kurdish language ckb-IQ in my app and when I switch to this language some characters are not connected to each other, and when I used ku it is connected, so after doing some debugs and when I added ku to the iSRTLLanguage() it behave same as ckb-IQ so I guess when we forceRightToLeft for Kurdish language it is corrupting the text.

First, I thought it was an Xcode issue so I created this StackOverflow question

https://stackoverflow.com/questions/59967897/xcode-kurdish-localization-issue

**Comment by MoathOthman** [comment]
@abdallahnh such issues sometimes caused by the font not supporting certain characters. maybe you can try another font. does the text looks fine without forcing right to left. or when changing the language from settings app.

**Comment by abdallahnh** [comment]
@MoathOthman it thought that at the beginning and I tried diff kurdish fonts, but as I said using ku it worked and using ckb didn't and the only diff is having ckb in isRTLLanguage() and when I added ku to the isRTLLanguage then both contained the issue

**Comment by MoathOthman** [comment]
@abdallahnh i just tried ckb-IQ on the demo project , seems fine. 
![Simulator Screen Shot - iPhone 11 - 2020-01-30 at 17 31 15](https://user-images.githubusercontent.com/1166727/73458478-66f17400-4386-11ea-841e-00b19a32a7d4.png)

**Comment by abdallahnh** [comment]
@MoathOthman where is the kurdish text :)

**Comment by MoathOthman** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-01-30 at 17 37 18](https://user-images.githubusercontent.com/1166727/73459029-3e1dae80-4387-11ea-8d19-2523e7286a56.png)
another sample taken from 
https://www.omniglot.com/writing/kurdish.htm

**Comment by abdallahnh** [comment]
@MoathOthman 
using ckb
![IMG_4A8A22E26DF2-1](https://user-images.githubusercontent.com/14108529/73458934-b59b1000-437e-11ea-8017-de96dfbd1499.jpeg)
using ku
![IMG_563EEC26BB84-1](https://user-images.githubusercontent.com/14108529/73459066-ebd88f80-437e-11ea-91a7-dd3ca1b293b7.jpeg)

see the diff please

**Comment by abdallahnh** [comment]
@MoathOthman please test this on your demo
ئۆە، دیارە پەیوەندیت بە ئینتەرنێت نەکردووە، تکایە دڵنیابە لە پەیوەندی ئینتەرنێت بکە و دووبارە بکەوە

**Comment by abdallahnh** [comment]
@MoathOthman I used the same font for both and still the same

**Comment by MoathOthman** [comment]
> @MoathOthman please test this on your demo
> ئۆە، دیارە پەیوەندیت بە ئینتەرنێت نەکردووە، تکایە دڵنیابە لە پەیوەندی ئینتەرنێت بکە و دووبارە بکەوە

seems fine as well.

**Comment by abdallahnh** [comment]
@MoathOthman 
are you setting the values from UI or by code, if you set it by code it will not work please confirm

**Comment by MoathOthman** [comment]
@abdallahnh by code(Localizable.string). I will push it on another branch.

**Comment by abdallahnh** [comment]
@MoathOthman AdobeArabicBold & droid-arabic-naskh

**Comment by abdallahnh** [comment]
@MoathOthman when i deal with ku like ckb, "make it an RTL" the text disconnected

**Comment by abdallahnh** [comment]
@MoathOthman thanks for your help, this was related to the Arabic font in our library
