### ISSUE TITLE
Language Change Design not working

### ISSUE THREAD

**Issue by rajendranVivensas** [MoathOthman/MOLH#6]
I have applied the language reset option. But the language change not applied exactly as needed. Change the language using set language option, and the design applied only when i close the app & reopen the app. Also some times Arabic to English change some layout changing from LTR to RTL. But the language text not updated.Keep the same language text.

Label inside the Tableview cell not aligned the correct language Direction. It affect only after restart the app.

**Comment by MoathOthman** [comment]
@rajendranVivensas MOLH will call reset function on Appdelegate if its implemented. 
You can check how its implemented in the demo. 
Regards ,
