### ISSUE TITLE
when change language to Urdu or Arabic and run app , texts font changed to this font 

### ISSUE THREAD

**Issue by ElSawyMohamed** [MoathOthman/MOLH#63]
[
![Screen Shot 2020-10-13 at 3 10 54 PM](https://user-images.githubusercontent.com/31069080/95864999-6f4bdc80-0d66-11eb-8d4a-0967564e0944.png)
](url)

**Comment by MoathOthman** [comment]
@ElSawyMohamed is this in the demo ?
